/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import edu.au.cc.gallery.tools.UserAdmin;
import edu.au.cc.gallery.tools.WebAdmin;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) throws Exception {
        String portString = System.getenv("JETTY_PORT");
	int port = 5000;
	if (portString != null && ! portString.equals(""))
            port = Integer.parseInt(portString);
    	WebAdmin.run(port);
    }

    private static String listUsers() {
        try {
            StringBuffer sb = new StringBuffer();
            UserDAO dao = Postgres.getUserDAO();
            for (User u : dao.getUsers()) {
                sb.append(u.toString());
            }
            return sb.toString();
        }
        catch (Exception ex) {
            return "[ERR]: " + ex.getMessage();
        }
    }
}
