/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery.ui;

import edu.au.cc.gallery.tools.UserAdmin;
import edu.au.cc.gallery.tools.WebAdmin;

import edu.au.cc.gallery.data.Postgres;
import edu.au.cc.gallery.data.UserDAO;
import edu.au.cc.gallery.data.User;

import static spark.Spark.*;
import spark.Response;

public class App {
    public static void main(String[] args) throws Exception {
        String portString = System.getenv("JETTY_PORT");
        if (portString == null || portString.equals(""))
            port(5000);
        else
            port(Integer.parseInt(portString));
        get("/users", (res, req) -> listUsers());
	get("/users/:username", (req, res) -> getUser(req.params(":username")));
	get("/adduser/:username/:password/:fullname", 
			(req, res) -> addUser(req.params(":username"), req.params(":password"), req.params(":fullname"), res));
    }

    private static UserDAO getUserDAO() throws Exception {
        return Postgres.getUserDAO();
    }

    private static String listUsers() {
        try {
            StringBuffer sb = new StringBuffer();
            UserDAO dao = getUserDAO();
            for (User u : dao.getUsers()) {
                sb.append(u.toString());
            }
            return sb.toString();
        }
        catch (Exception ex) {
            return "[ERR]: " + ex.getMessage();
        }
    }

    private static String getUser(String username) {
        try {
            UserDAO dao = getUserDAO();
	    return dao.getUserByUsername(username).toString();
	}
	catch (Exception ex) {
            return "[ERR]: " + ex.getMessage();
	}
    }

    private static String addUser(String username, String password, String fullName, Response r) {
        try {
            UserDAO dao = getUserDAO();
	    dao.addUser(new User(username, password, fullName));
	    r.redirect("/users");
	    return "";
	}
	catch (Exception ex) {
            return "[ERR]: " + ex.getMessage();
	}
    }
}
